# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['gesture.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('assets', 'assets'),
        ('server/web', 'server/web'),
    ],
    hiddenimports=[
        'gesture_engine.camera',
        'gesture_engine.capture',
        'gesture_engine.geometry',
        'gesture_engine.core.matching',
        'gesture_engine.core.wake_gate',
        'gesture_engine.core.confirmation',
        'gesture_engine.core.movement',
        'gesture_engine.core.handlers',
        'gesture_engine.core.handlers.action_queue',
        'gesture_engine.core.handlers.ha_handler',
        'gesture_engine.core.handlers.ir_handler',
        'gesture_engine.core.handlers.pc_handler',
        'gesture_engine.overlay',
        'gesture_engine.runtime',
        'gesture_engine.server_runner',
        'gesture_engine.core.workers',
        'gesture_engine.core.actions',
        'mediapipe',
        'mediapipe.tasks',
        'mediapipe.tasks.vision',
        'mediapipe.framework.formats',
        'mediapipe.framework.formats.landmark_pb2',
        'cv2',
        'numpy',
        'fastapi',
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'zeroconf',
        'requests',
        'pyautogui',
        'server',
        'server.main',
        'server.file',
        'server.models',
        'server.startup',
        'server.config_validation',
        'server.homeassistant',
        'server.ha_client',
        'server.ha_config',
        'server.ha_entities',
        'server.ha_pairing',
        'server.ha_services',
        'server.ha_transport',
        'server.discovery',
        'server.events',
        'server.streamer',
        'server.timing',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=['_pyi_rthook.py'],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='sensee-x64',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='sensee-x64',
)
